services:
  - type: web
    name: hr-bot-api
    env: node
    rootDir: ./
    buildCommand: npm install && npm run build
    startCommand: node dist/src/app.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: SALESFORCE_CLIENT_ID
        sync: false
      - key: SALESFORCE_CLIENT_SECRET
        sync: false
      - key: SALESFORCE_USERNAME
        sync: false
      - key: SALESFORCE_PASSWORD
        sync: false
      - key: SALESFORCE_SECURITY_TOKEN
        sync: false
